ALTER TABLE "Car" ADD COLUMN "registeredById" INTEGER;
ALTER TABLE "Car" ADD CONSTRAINT "Car_registeredById_fkey" FOREIGN KEY ("registeredById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
